# Generated by Django 4.0.3 on 2022-12-02 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='content',
        ),
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.ManyToManyField(blank=True, to='task2.content'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task2.course'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task2.student'),
        ),
    ]
